name: 'My composite action'
description: 'This is the custom composite action'
inputs:
  custom-input-name:
    description: 'Description for the input'
    required: true
    default: 'Yes'
runs:
  using: 'composite'
  steps:
    - name: Check input
      if: inputs.custom-input-name == 'Yes'
      run: echo 'Input is set'
      shell: bash
