name: Basic workflow file
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Base job 1
        run: echo 'Bismillah'
      - name: Use Reusable workflow
        uses: ./.github/workflows/reusable.yml
