name: Use GitHub Secrets

on:
  workflow_dispatch

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use the Secret
        run: |
          # Access the secret using the environment variable
          API_KEY=$MY_API_KEY

          # Print the secret value
          echo "My API Key is: $API_KEY"

        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
