name: Continue on Error Example

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test
      run: |
        echo "Testing the project..."
        exit 1
      continue-on-error: true

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Report
      run: |
        echo "Uploading the report..."
