name: Using a reusable workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Print text
         run: |
           echo "I'm from the original workflow"

  get_greet:
    uses: ./.github/workflows/reusable_details.yml

  post_greeting:
    runs-on: ubuntu-latest
    needs: get_greet
    steps:
      - name: Post greeting
        run: echo ${{ needs.get_greet.outputs.greet_text }}, Harmony!
