name: Continue on Error Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        # Simulate a build error by running a command that fails
        echo "Building the project..."
        exit 1

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Tests
      run: |
        # Add test commands here
        echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      run: |
        # Add deployment commands here
        echo "Deploying to production..."

