name: Using a reusable workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Get Code
         uses: actions/checkout@v4
       - name: Print text
         run: |
           echo "I'm from the original workflow"
       - name: Print from reusable
         uses: ./.github/workflows/reusable_details.yml
