name: Using Env Vars

on:
  workflow_dispatch

env:
  PLUGIN_VERSION: 4.2.1

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UPDATE_DATE: "October 1, 2023"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment Variable
        run: echo "The plugin version is $PLUGIN_VERSION. It was updated on $UPDATE_DATE."
