name: Use GitHub Secrets Example

on:
  workflow_dispatch

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the Secret
        run: |
          # Access the secret using the environment variable
          API_KEY=$MY_API_KEY

          # Print the secret value
          echo "My API Key is: $API_KEY"

          # You can use the secret in your scripts or commands
          # For example, if it's an API key, you can use it to make API requests

        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
