name: Using a reusable workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Print text
         run: |
           echo "I'm from the original workflow"

  greet:
    uses: ./.github/workflows/reusable_details.yml
    with:
      provide-name: 'Harmony'
