name: Reusuable details workflow
on:
  workflow_call:
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable step 1
        run: echo "Coming from Reusable step 1"
      - name: Reusable step 2
        run: echo "Coming from Reusable step 2"
