name: Script Injection Prevention

on:
  issues:
    types:
      - opened

jobs:
  check_title_job:
    runs-on: ubuntu-latest
    name: A job to prevent SI
    steps:
      - name: Check Issue title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          # title="${{ github.event.issue.title }}"
          if [[ $ISSUE_TITLE == *"bug"* ]]; then
          echo "Issue is about a bug"
          else
          echo "Issue is not about a bug"
          fi
