name: Use Composite Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Base job
        run: echo 'I am from the Caller workflow'
      - name: Use composite
        uses: ./.github/actions/test-composite
        with:
          custom-input-name: 'Yes'
  
